---
- name: "Create jenkins service"
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0644
  become: yes

- name: "Enable jenkins service"
  service:
    name: jenkins.service
    enabled: yes
  become: yes

- name: "Start jenkins service"
  service:
    name: jenkins.service
    state: started
  become: yes


